target: deploy.robot.koch.KochFollowerWithCamera
com: COM8
robot_id: koch_follower
camera_configs:
  front_camera:
    index_or_path: /dev/video2
    width: 640
    height: 480
    fps: 10
use_lock: True