target: deploy.robot.sim_pybullet.AbsJointRobot
action_dim: 9
action_dtype: float64
robot_urdf_path: "franka_panda/panda.urdf"
initial_joint_positions: [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785]
gripper_joint_indices: [9, 10]
gripper_width: 0.04
use_gui: true