name: diffusion_policy
module_path: policy.diffusion_policy
config_class: DiffusionPolicyConfig
model_class: DiffusionPolicyModel
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
model_args:
  action_dim: 14
  state_dim: 14
  horizon: 100
  n_action_steps: 100
  n_obs_steps: 1
  num_inference_steps: 10
  noise_scheduler: "ddpm"
  noise_scheduler_kwargs: {}
  obs_encoder: "resnet18"
  obs_encoder_kwargs: {}
  action_encoder: "temporal"
  action_encoder_kwargs: {}
  action_decoder: "temporal"
  action_decoder_kwargs: {}
  use_pretrained_weights: true
  pretrained_model_path: null
  # Image sizes will be set from task config
  image_sizes: null
data_processor: StateToQposProcessor
data_collator: data_collator_wrapper
trainer_class: Trainer
