name: divla
module_path: policy.divla
config_class: DiVLAConfig
model_class: DiVLAPolicy
pretrained_config:
  model_name_or_path: "Qwen/Qwen2-VL-2B-Instruct"
  is_pretrained: false
model_args:
  action_dim: 14
  state_dim: 14
  horizon: 100
  vision_encoder: "clip"
  language_model: "qwen2vl"
  fusion_method: "cross_attention"
  use_reasoning: false
  reasoning_tokens: 10
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: Trainer
