name: mlp
module_path: policy.mlp
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null  # Use framework default trainer
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
model_args:
  # Model architecture parameters
  state_dim: 39          # Input state dimension
  action_dim: 28         # Output action dimension  
  num_layers: 3          # Number of layers in the MLP
  hidden_dim: 256        # Hidden layer dimension
  activation: "relu"     # Activation function: relu, tanh, sigmoid, leaky_relu, gelu
  dropout: 0.0           # Dropout rate (0.0 to disable)
  use_camera: false      # Whether to use image modality (state only by default)
  image_dim: null        # Flattened image dimension (calculated automatically)
  # Training parameters
  chunk_size: 1          # Chunk size (number of action steps to predict)
