name: mlp_large
module_path: policy.mlp
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null  # Use framework default trainer
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
model_args:
  # Model architecture parameters - Large Model
  state_dim: 14          # Input state dimension
  action_dim: 14         # Output action dimension  
  num_layers: 5          # More layers for increased capacity
  hidden_dim: 512        # Larger hidden layer dimension
  activation: "relu"     # Activation function
  dropout: 0.2           # Higher dropout for regularization
  use_camera: false      # Whether to use image modality
  image_dim: null        # Flattened image dimension (calculated automatically)
  # Training parameters
  learning_rate: 5e-4    # Lower learning rate for larger model
  chunk_size: 1          # Chunk size
