name: mlp_small
module_path: policy.mlp
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null  # Use framework default trainer
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
model_args:
  # Model architecture parameters - Small Model
  state_dim: 14          # Input state dimension
  action_dim: 14         # Output action dimension  
  num_layers: 2          # Minimal layers for simplicity
  hidden_dim: 128        # Smaller hidden layer dimension
  activation: "tanh"     # Tanh activation often works well for smaller networks
  dropout: 0.0           # No dropout for small model
  use_camera: false      # Whether to use image modality
  image_dim: null        # Flattened image dimension (calculated automatically)
  # Training parameters
  learning_rate: 2e-3    # Higher learning rate for faster convergence
  chunk_size: 1          # Chunk size
