name: octo
module_path: policy.octo
pretrained_config:
  model_name_or_path: "facebook/opt-125m"
  is_pretrained: false
model_args:
  action_dim: 14
  state_dim: 14
  chunk_size: 50
  jax_checkpoint: 'hf://rail-berkeley/octo-small-1.5'
  

