name: "pi0fast"
module_path: "policy.pi0"
config_class: "PI0FlowMatchingConfig"
model_class: "PI0FlowMatching"
data_processor: "get_data_processor"
data_collator: "get_data_collator"
trainer_class: "PI0Trainer"

# Model parameters - optimized for speed
model_args:
  state_dim: 14
  action_dim: 14
  camera_names: ["primary"]
  chunk_size: 25  # Smaller chunk size for faster inference
  n_action_steps: 25
  freeze_vision_encoder: true
  train_expert_only: false
  train_state_proj: true
  
# Training parameters - optimized for speed
config_params:
  # Input / output structure
  n_obs_steps: 1
  chunk_size: 25  # Smaller chunk size
  n_action_steps: 25
  
  # Normalization mapping
  normalization_mapping:
    VISUAL: "identity"
    STATE: "mean_std"
    ACTION: "mean_std"
  
  # Padding dimensions
  max_state_dim: 32
  max_action_dim: 32
  proj_width: 512  # Smaller projection width for speed
  
  # Image preprocessing
  resize_imgs_with_padding: [224, 224]
  
  # Empty cameras
  empty_cameras: 0
  
  # Tokenizer
  tokenizer_max_length: 32  # Shorter max length for speed
  
  # Decoding
  num_steps: 5  # Fewer denoising steps for speed
  
  # Attention utils
  use_cache: true
  
  # Finetuning settings
  freeze_vision_encoder: true
  train_expert_only: false
  train_state_proj: true
  attention_implementation: "eager"  # Use eager attention for speed
  
  # Training presets
  optimizer_lr: 0.0001
  optimizer_betas: [0.9, 0.95]
  optimizer_eps: 1e-08
  optimizer_weight_decay: 1e-10
  optimizer_grad_clip_norm: 10
  
  scheduler_warmup_steps: 500  # Shorter warmup
  scheduler_decay_steps: 15000  # Shorter decay
  scheduler_decay_lr: 2.5e-06
