name: qwen25dp
module_path: policy.qwen25dp
config_class: QwenVLPolicyConfig
model_class: QwenVLForPolicy
pretrained_config:
  model_name_or_path: "Qwen/Qwen2.5-VL-3B-Instruct"
  is_pretrained: false
  vlm_model_name_or_path: "Qwen/Qwen2.5-VL-3B-Instruct"
model_args:
  policy_action_dim: 14
  policy_state_dim: 14
  policy_prediction_horizon: 100
  lora_enable: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  lora_bias: "none"
  lora_task_type: "CAUSAL_LM"
  lora_module: "vit,llm,merger"
  bits: 16
  bf16: true
  fp16: false
  gradient_checkpointing: true
  freeze_backbone: false
  lora_lr: 1e-4
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: Trainer
