name: rdt
module_path: policy.rdt
config_class: RDTConfig
model_class: RDTModel
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
model_args:
  action_dim: 14
  state_dim: 14
  horizon: 100
  n_obs_steps: 1
  n_action_steps: 100
  obs_encoder: "resnet18"
  action_encoder: "temporal"
  action_decoder: "temporal"
  use_pretrained_weights: true
  pretrained_model_path: null
data_processor: null
data_collator: null
trainer_class: null
