python openx_rlds_to_h5py.py --name berkeley_fanuc_manipulation
python openx_rlds_to_h5py.py --name berkeley_cable_routing
python openx_rlds_to_h5py.py --name ucsd_kitchen_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name viola
python openx_rlds_to_h5py.py --name stanford_hydra_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name dlr_edan_shared_control_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name furniture_bench_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name cmu_stretch
python openx_rlds_to_h5py.py --name austin_buds_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name language_table
python openx_rlds_to_h5py.py --name taco_play
python openx_rlds_to_h5py.py --name toto
python openx_rlds_to_h5py.py --name austin_sirius_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name jaco_play
python openx_rlds_to_h5py.py --name roboturk
python openx_rlds_to_h5py.py --name bc_z
python openx_rlds_to_h5py.py --name droid
# python openx_rlds_to_h5py.py --name fmb
python openx_rlds_to_h5py.py --name nyu_franka_play_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name utaustin_mutex
python openx_rlds_to_h5py.py --name bridge_orig
python openx_rlds_to_h5py.py --name berkeley_autolab_ur5
python openx_rlds_to_h5py.py --name kuka
python openx_rlds_to_h5py.py --name dobbe
python openx_rlds_to_h5py.py --name fractal20220817_data
python openx_rlds_to_h5py.py --name austin_sailor_dataset_converted_externally_to_rlds
python openx_rlds_to_h5py.py --name iamlab_cmu_pickup_insert_converted_externally_to_rlds