# 新的灵活数据集配置格式
datasets:
  - name: "aloha_transfer_cube"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['/home/wz/project/IL-Studio/data/transfer_scripted']
      camera_names: ['primary']
      chunk_size: 100
      ctrl_space: 'joint'
      ctrl_type: 'abs'

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size: [256, 256]
action_normalize: "zscore"
state_normalize: "zscore"
episode_len: 400

# Data processing parameters moved to training config
