dataset_dir:
  - '/home/wz/project/IL-Studio/data/transfer_scripted'
episode_len: 400
camera_names:
  - primary
dataset_class: AlohaSimDataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size: [256, 256]
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 100

# Data processing parameters moved to training config
