# 向后兼容示例：旧格式仍然可以正常工作

# 这是原有的配置格式，完全兼容
dataset_dir:
  - 'data/sim_transfer_cube_scripted'
  - 'data/additional_dataset'

episode_len: 400
camera_names:
  - primary
dataset_class: AlohaSimDataset
ctrl_type: abs
ctrl_space: joint

# 任务特定参数
action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 64

# 任务特定数据处理参数
use_reasoning: false
use_prev_subtask: false

# 这个配置文件会被 _load_data_legacy_format 函数处理
# 完全保持原有的行为和兼容性
