# 新的灵活数据集配置格式
datasets:
  - name: "d4rl_door_expert"
    class: "D4RLDataset"
    args:
      dataset_path_list: ['D4RL/door/expert-v2']
      chunk_size: 1
      ctrl_space: 'joint'
      ctrl_type: 'abs'
      is_h5: False

# Task-specific parameters that will override policy configs
action_dim: 28
state_dim: 39
action_normalize: "identity"
state_normalize: "identity"
episode_len: 200

# Data processing parameters moved to training config
