dataset_dir:
  - 'data/sim_transfer_scripted'
episode_len: 400
camera_names:
  - primary
dataset_class: AlohaSimDataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size_primary: "(256, 256)"
image_size_wrist: "(256, 256)"
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 100

# Data processing parameters moved to training config
