# 新的灵活数据集配置格式
datasets:
  - name: "droid_100"
    class: "data_utils.datasets.droid.DroidDataset"
    args:
      dataset_dir: "/inspire/hdd/project/robot-action/public/data/droid/"
      name: "droid_100"
      version: "1.0.0"
      filter_dict_path: null

episode_len: 1000
action_dim: 8
state_dim: 8
ctrl_space: "joint"
ctrl_type: "abs"