# 新的灵活数据集配置格式
datasets:
  - name: "droid_mini"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/droid_mini"]
      camera_names: ['left', 'right']

episode_len: 1000
