datasets:
  - name: "example_dataset_1"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['data/sim_transfer_cube_scripted']
      camera_names: ['primary']
      chunk_size: 100
      ctrl_space: 'joint'
      ctrl_type: 'abs'
    # mask配置与args同级
    action_norm_mask: [-1]
    state_norm_mask: [-1]
      
  - name: "example_dataset_2"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ['data/libero']
      camera_names: ['top']
    # Boolean数组格式
    action_norm_mask: [true, true, true, true, true, true, false]

  - name: "example_dataset_3"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ['data/another_dataset']
      camera_names: ['primary']
    # 不指定mask，使用默认行为

action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore" 
state_normalize: "zscore"
episode_len: 400
use_reasoning: false
use_prev_subtask: false

