# 新的灵活数据集配置格式示例
# 支持多个数据集，每个数据集独立配置

# 数据集列表 - 支持多个不同类型的数据集
datasets:
  # 第一个数据集：标准 EpisodicDataset
  - name: "main_dataset"
    class: "data_utils.datasets.EpisodicDataset"
    args:
      dataset_path_list: ['data/sim_transfer_cube_scripted']
      camera_names: ['primary', 'wrist']
      chunk_size: 100
      ctrl_space: 'joint'
      ctrl_type: 'abs'

  # 第二个数据集：RLDS 格式数据集
  - name: "rlds_dataset"
    class: "data_utils.datasets.rlds_wrapper.WrappedTFDSDataset"
    args:
      dataset_path_list: ['data/rlds_dataset']
      camera_names: ['primary']
      chunk_size: 64
      ctrl_space: 'ee'
      ctrl_type: 'delta'

  # 第三个数据集：自定义数据集类
  - name: "custom_dataset"
    class: "my_custom_module.MyCustomDataset"
    args:
      data_path: 'data/custom_data'
      camera_names: ['primary']
      custom_param1: 'value1'
      custom_param2: 42
      # 任何自定义参数都可以在这里定义

# 任务特定参数
action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore"
state_normalize: "zscore"

# 其他任务参数
episode_len: 400
use_reasoning: false
use_prev_subtask: false
