dataset_dir:
  - '/inspire/hdd/project/robot-action/public/data/act_aloha/sim_insertion_human'
camera_names:
  - primary
dataset_class: AlohaSimDataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size_primary: "(640, 480)"
image_size_wrist: "(640, 480)"
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 50
