# 新的灵活数据集配置格式
datasets:
  - name: "lerobot_metaworld"
    class: "WrappedLerobotDataset"
    args:
      dataset_path_list: [lerobot/metaworld_mt50]
      chunk_size: 64
      ctrl_space: 'ee'
      ctrl_type: 'abs'

# Task-specific parameters
action_dim: 4
state_dim: 4
image_size: [480, 480]
action_normalize: "zscore"
state_normalize: "zscore"

