# 新的灵活数据集配置格式
datasets:
  - name: "libero_goal"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_goal/h5"]
      camera_names: ['primary']

episode_len: 400
