dataset_dir:
  - "/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_object/h5v2"
episode_len: 400
camera_names:
  - primary
dataset_class: LiberoDataset
ctrl_type: delta
ctrl_space: ee

# Task-specific parameters that will override policy configs
action_dim: 7
state_dim: 7
image_size: [256, 256]
action_normalize: "minmax"
state_normalize: "minmax"
chunk_size: 50
