# 新的灵活数据集配置格式
datasets:
  - name: "libero_10"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_10/h5"]
      camera_names: ['top']
  - name: "libero_object"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_object/h5"]
      camera_names: ['top']
  - name: "libero_goal"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_goal/h5"]
      camera_names: ['top']
  - name: "libero_spatial"
    class: "EpisodicDataset"
    args:
      dataset_path_list: ["/inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero/libero_spatial/h5"]
      camera_names: ['top']

episode_len: 400
