# 新的灵活数据集配置格式
datasets:
  - name: "nut_assembly_square_panda"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/square/ph']
      camera_names: ['primary']
      ctrl_space: 'ee'
      ctrl_type: 'delta'

episode_len: 400
