# 新的灵活数据集配置格式
datasets:
  - name: "robomimic_square_ph"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/square/ph']
      camera_names: ['primary']
      ctrl_space: 'ee'
      ctrl_type: 'delta'

episode_len: 400
action_dim: 8
state_dim: 8
action_normalize: "zscore"
state_normalize: "zscore"