# 新的灵活数据集配置格式
datasets:
  - name: "robomimic_square_ph"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/square/ph']
      camera_names: ['primary']
      chunk_size: 50
      ctrl_space: 'ee'
      ctrl_type: 'delta'
  - name: "robomimic_square_mh"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/square/mh']
      camera_names: ['primary']
      chunk_size: 50
      ctrl_space: 'ee'
      ctrl_type: 'delta'

# Task-specific parameters that will override policy configs
action_dim: 7
state_dim: 7
image_size: [256, 256]
action_normalize: "minmax"
state_normalize: "minmax"
episode_len: 400
