dataset_dir:
  - '/home/agilex/zxc/cobot_magic/collect_data/cut_steak/cut_steak'
episode_len: 400
camera_names:
  - primary
  - wrist_left
  - wrist_right
dataset_class: AlohaSIIDataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size_primary: "(256, 256)"
image_size_wrist: "(256, 256)"
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 100
