dataset_dir:
  - '/inspire/hdd/project/robot-action/public/data/sfo_train/pick_two_objects'
camera_names:
  - primary
  - wrist_left
  - wrist_right
dataset_class: AlohaSIIv2Dataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size_primary: "(256, 256)"
image_size_wrist: "(256, 256)"
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 100
