datasets:
  - name: "sim_transfer_cube_scripted"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['data/sim_transfer_cube_scripted']
      camera_names: ['primary']
      chunk_size: 100
      ctrl_space: 'joint'
      ctrl_type: 'abs'
  - name: "sim_transfer_cube_human"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['data/sim_transfer_cube_human']
      camera_names: ['primary']
      chunk_size: 100
      ctrl_space: 'joint'
      ctrl_type: 'abs'

action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore"
state_normalize: "zscore"

episode_len: 400
use_reasoning: false
use_prev_subtask: false