dataset_dir:
  - 'data/sim_transfer_cube_scripted'
episode_len: 400
camera_names:
  - primary
dataset_class: AlohaSimDataset
ctrl_type: abs
ctrl_space: joint

# Task-specific parameters
action_dim: 14
state_dim: 14
image_size_primary: "(640, 480)"
image_size_wrist: "(640, 480)"
action_normalize: "zscore"
state_normalize: "zscore"
chunk_size: 64

# Task-specific data processing parameters
use_reasoning: false
use_prev_subtask: false