# 新的灵活数据集配置格式
datasets:
  - name: "transfer_human"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/act_aloha/sim_transfer_cube_human']
      camera_names: ['primary']
      chunk_size: 50
      ctrl_space: 'joint'
      ctrl_type: 'abs'

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore"
state_normalize: "zscore"
