# 新的灵活数据集配置格式
datasets:
  - name: "transfer_cube_top"
    class: "AlohaSimDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/wangzheng-240308120196/act-plus-plus-main/data/sim_transfer_cube_scripted']
      camera_names: ['primary']
      chunk_size: 50
      ctrl_space: 'joint'
      ctrl_type: 'abs'

# Task-specific parameters that will override policy configs
action_dim: 14
state_dim: 14
image_size: [640, 480]
action_normalize: "zscore"
state_normalize: "zscore"
episode_len: 400

# Data processing parameters moved to training config
