target: deploy.teleoperator.iphone.IPhonePhyphox

# Controller settings
shm_name: "ilstd_teleop_controller"
action_dim: 7
action_dtype: "float64"
freq: 25.0

# Device-specific settings
phyphox_ip: '172.20.10.1'
phyphox_port: '80'
dt: 0.5
