target: deploy.teleoperator.keyboard.KeyboardTeleop

# Controller settings
shm_name: "ilstd_teleop_controller"
action_dim: 7
action_dtype: "float64"
freq: 10.0

# Device-specific settings
delta_scale: 5.0