target: deploy.teleoperator.koch_leader.KochLeader

# Controller settings
shm_name: "ilstd_teleop_controller"
action_dim: 7
action_dtype: "float64"
freq: 10.0

# Device-specific settings
com: COM7
robot_id: koch_leader
elbow_drive_mode: 0