target: deploy.teleoperator.so101_leader.So101Leader

# Controller settings
shm_name: "ilstd_teleop_controller"
action_dim: 6
action_dtype: "float64"
freq: 10.0

# Device-specific settings
com: COM3
robot_id: so101_leader
elbow_drive_mode: 0
