type: aloha
# Example fields consumed by benchmark.aloha.AlohaSimEnv
task: sim_transfer_cube_scripted
max_timesteps: 400
ctrl_space: joint
ctrl_type: abs
camera_ids: "[0]"
image_size_primary: "(640, 480)"
image_size_wrist: "(320, 240)"

