type: panda_gym
# Example fields consumed by benchmark.panda_gym.PandaGymEnv
# Available tasks: PandaReach, PandaPush, PandaSlide, PandaPickAndPlace, PandaStack, PandaFlip
task: PandaReach
max_timesteps: 50
ctrl_space: ee  # 'ee' or 'joint'
ctrl_type: abs  # fixed to 'abs' for PandaGym
use_camera: true
render_mode: rgb_array  # 'rgb_array' or 'human'
renderer: Tiny  # 'Tiny' or 'OpenGL'
use_dense_reward: false  # false for sparse reward, true for dense reward
