type: panda_gym
# Example configuration for PandaGym with dense reward
# Available tasks: PandaReach, PandaPush, PandaSlide, PandaPickAndPlace, PandaStack, PandaFlip
task: PandaPickAndPlace
max_timesteps: 100
ctrl_space: ee  # 'ee' or 'joint'
ctrl_type: abs  # fixed to 'abs' for PandaGym
use_camera: true
render_mode: rgb_array  # 'rgb_array' or 'human'
renderer: OpenGL  # 'Tiny' or 'OpenGL' - OpenGL provides better rendering quality
use_dense_reward: true  # true for dense reward (easier learning)
